name: Java CI com Maven (Fluxo por Features)

on:
  push:
    branches:
      - main
      - develop
      - '**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o codigo do repositorio
        uses: actions/checkout@v4

      - name: Configurar o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Compilar e Executar Testes com o Maven
        run: mvn clean test